### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined - Windows OS

### ISSUE THREAD

**Issue by rrmanzano** [zoho/zohocrm-typescript-sdk#4]
Hi, apparently there is an issue when we use the SDK in Windows OS, if I try to retrieve a record from Zoho I am receiving this error:

`
(node:23516) UnhandledPromiseRejectionWarning: Error: nullTypeError: Cannot read property 'hasOwnProperty' of undefined      
    at CommonAPIHandler.<anonymous> (C:\zoho-test\node_modules\@zohocrm\typescript-sdk\routes\middlewares\common_api_handler.ts:270:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\zoho-test\node_modules\@zohocrm\typescript-sdk\routes\middlewares\common_api_handler.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
`

I found in line 216 (File "common_api_handler.ts", see the image below) that the code is splitting the "className" by "/" but in Windows OS is a different format when we are working with paths, this code is generating an "index" = -1 and that is the root cause.

![image](https://user-images.githubusercontent.com/19593017/121294787-946ffb00-c8b3-11eb-9fb7-3f7cfa40d55d.png)

There are probably more parts where the same logic is being implemented, but making this simple change in the code could be a solution (and could be a cross-platform solution):

Before:
`
let baseName = className.split("/");
`

After:
`
let baseName = className.replace(/\\/gm, '/').split("/");
`

I already tested that change in my local environment and is working fine.

Thanks.

**Comment by raja-k-7453** [comment]
Thanks, @rrmanzano  for your contribution. We will make the necessary changes to avoid such errors in the next release.
