### ISSUE TITLE
Typescript fails on shipped .ts source files when using stricter tsconfig

### ISSUE THREAD

**Issue by Js-Brecht** [zoho/zohocrm-typescript-sdk#6]
Because the original `.ts` modules are included in the shipped package, and they're right next to the build artifact, they are automatically typechecked by Typescript.

The problem with this is if you are using a stricter `tsconfig.json` than what was used in this sdk, it will fail.  The specific issue we are having is regarding the `"strictPropertyInitialization": false` setting; we do not turn off `strictPropertyInitialization` in our projects.  When we use this sdk, we cannot build the project because you _do_ turn off `strictPropertyInitialization`, and typescript isn't using the `tsconfig.json` from your project.

This is what we wind up with (380 times, in different modules, for different class properties):
```
error TS2564: Property 'categoryMethod' has no initializer and is not definitely assigned in the constructor.
```

We cannot exclude this project, specifically, from being typechecked because the `exclude` property does not work on files that are explicitly `import`ed into a module.
We cannot use `skipLibCheck: true` either, because that only tells it to ignore `.d.ts` files.

In essence, because Typescript sees `.ts` files next to the build artifacts, it will prefer those, and we cannot skip their type checking.  The only real way we can work around this is to reduce the type safety of our own code.

**Comment by raja-k-7453** [comment]
@Js-Brecht Thanks for notifying us. We're currently working on it and will resolve it soon.

**Comment by pascalvgemert** [comment]
@raja-7453 Is this issue resolved? I'm still encountering this issue with the latest version of the package. Or is there any workaround and keeping strict mode on for our project? @Js-Brecht Did you find anything?

**Comment by raja-k-7453** [comment]
@pascalvgemert The changes are available in this package:
https://www.npmjs.com/package/@zohocrm/typescript-sdk-2.1

Please refer to this repository:
https://github.com/zoho/zohocrm-typescript-sdk-2.1
